#!/usr/bin/env python3

from .batch_000 import (
    Accel,
    Activ,
    Admas,
    AdmeshGlobal,
    AdmeshSet,
    AdmeshStateShell,
    AdmeshStateSh3n,
    ALEBcs,
    ALEClose,
)

from .batch_001 import (
    ALEGridDisp,
    ALEGridDonea,
    ALEGridLaplacian,
    ALEGridSpring,
    ALEGridStandard,
    ALEGridVolume,
    ALEGridZero,
    ALELinkVel,
    ALEMat,
)

from .batch_002 import (
    ALEMuscl,
    ALESolverFint,
    Ams,
    Analy,
    AnimVers,
    Bcs,
    BcsCyclic,
    BcsLagmul,
    Beam,
)

from .batch_003 import (
    Begin,
    BemDaa,
    BemFlow,
    Box,
    BoxBox,
    Brick,
    Bric20,
    CheckRfileOff,
    Cload,
)

from .batch_004 import (
    Cluster,
    Cnode,
    Convec,
    CylJoint,
    Damp,
    DampInter,
    Def_Shell,
    Def_Solid,
    DefaultInterType2,
)

from .batch_005 import (
    DefaultInterType7,
    DefaultInterType11,
    DefaultInterType19,
    DefaultInterType24,
    DefaultInterType25,
    DfsDetcord,
    DfsDetline,
    DfsDetlineNode,
    DfsDetplan,
)

from .batch_006 import (
    DfsDetplanNode,
    DfsDetpoint,
    DfsDetpointNode,
    DfsLaser,
    DfsWavSha,
    Drape,
    EbcsFluxout,
    EbcsGradp0,
    EbcsInip,
)

from .batch_007 import (
    EbcsIniv,
    EbcsInlet,
    EbcsMonvol,
    EbcsNormv,
    EbcsNrf,
    EbcsPres,
    EbcsValvin,
    EbcsValvout,
    EbcsVel,
)

from .batch_008 import (
    Eig,
    Encrypt,
    End,
    EosCompaction,
    EosGruneisen,
    EosIdealGas,
    EosIdealGasVt,
    EosLinear,
    EosLszk,
)

from .batch_009 import (
    EosMurnaghan,
    EosNasg,
    EosNobleAbel,
    EosOsborne,
    EosPolynomial,
    EosPuff,
    EosSesame,
    EosStiffGas,
    EosTillotson,
)

from .batch_010 import (
    Eref,
    EulerMat,
    Fail,
    FailAlter,
    FailBiquad,
    FailChang,
    FailCockcroft,
    FailConnect,
    FailEmc,
)

from .batch_011 import (
    FailEnergy,
    FailFabric,
    FailFld,
    FailGene1,
    FailGurson,
    FailHashin,
    FailHcDsse,
    FailJohnson,
    FailLadDama,
)

from .batch_012 import (
    FailMullinsOr,
    FailNxt,
    FailOrthbiquad,
    FailOrthstrain,
    FailPuck,
    FailRtcl,
    FailSahraei,
    FailSnconnect,
    FailSpalling,
)

from .batch_013 import (
    FailTab1,
    FailTbutcher,
    FailTensstrain,
    FailUseri,
    FailVisual,
    FailWierzbicki,
    FailWilkins,
    FrameFix,
    FrameMov,
)

from .batch_014 import (
    FrameMov2,
    FrameNod,
    FricOrient,
    Friction,
    Func2d,
    Funct,
    FunctSmooth,
    Fxbody,
    Gauge,
)

from .batch_015 import (
    GaugeSph,
    Gjoint,
    Grav,
    Grbeam,
    Grbric,
    Grnod,
    Grpart,
    Grquad,
    Grsh3n,
)

from .batch_016 import (
    Grshel,
    Grspri,
    Grtria,
    Grtrus,
    HeatMat,
    Impacc,
    Impdisp,
    ImpdispFgeo,
    Impflux,
)

from .batch_017 import (
    Implicit,
    Imptemp,
    Impvel,
    ImpvelFgeo,
    ImpvelLagmul,
    InibeamAux,
    InibeamFull,
    Inibri,
    Inicrack,
)

from .batch_018 import (
    Inigrav,
    Inimap1d,
    Inimap1dFile,
    Inimap2d,
    Inimap2dFile,
    Iniqua,
    IniquaDens,
    IniquaEner,
    IniquaEpsp,
)

from .batch_019 import (
    IniquaStress,
    InisheAux,
    Inish3Aux,
    InisheEpsp,
    Inish3Epsp,
    InisheEpspF,
    Inish3EpspF,
    InisheFail,
    InisheOrthLoc,
)

from .batch_020 import (
    Inish3OrthLoc,
    InisheOrtho,
    Inish3Ortho,
    InisheScaleYld,
    Inish3ScaleYld,
    InispriFull,
    InisheStraF,
    Inish3StraF,
    InisheStraFGlob,
)

from .batch_021 import (
    Inish3StraFGlob,
    InisheStrsF,
    Inish3StrsF,
    InisheStrsFGlob,
    Inish3StrsFGlob,
    InisheThick,
    Inish3Thick,
    InispriFull,
    Inista,
)

from .batch_022 import (
    Initemp,
    InitrussFull,
    Inivel,
    InivelAxis,
    InivelFvm,
    InivelNode,
    Inivol,
    InterHertzType17,
    InterLagdtType7,
)

from .batch_023 import (
    InterLagmulType2,
    InterLagmulType7,
    InterLagmulType16,
    InterLagmulType17,
    InterSub,
    InterType1,
    InterType2,
    InterType3,
    InterType5,
)

from .batch_024 import (
    InterType6,
    InterType7,
    InterType8,
    InterType9,
    InterType10,
    InterType11,
    InterType12,
    InterType14,
    InterType15,
)

from .batch_025 import (
    InterType18,
    InterType19,
    InterType21,
    InterType22,
    InterType23,
    InterType24,
    InterType25,
    Ioflag,
    Key,
)

from .batch_026 import (
    Lagmul,
    LeakMat,
    Line,
    LoadCentri,
    LoadPblast,
    LoadPfluid,
    MadymoExfem,
    MatBKEps,
    MatGas,
)

from .batch_027 import (
    MatLaw0,
    MatLaw1,
    MatPlasJohns,
    MatPlasZeril,
    MatLaw3,
    MatLaw4,
    MatLaw5,
    MatLaw6,
    MatKEps,
)

from .batch_028 import (
    MatLaw10,
    MatLaw11,
    MatLaw12,
    MatLaw14,
    MatLaw15,
    MatLaw16,
    MatLaw18,
    MatLaw19,
    MatLaw20,
)

from .batch_029 import (
    MatLaw21,
    MatLaw22,
    MatLaw23,
    MatLaw24,
    MatLaw25,
    MatLaw26,
    MatLaw27,
    MatLaw28,
    MatLaw32,
)

from .batch_030 import (
    MatLaw33,
    MatLaw34,
    MatLaw35,
    MatLaw36,
    MatLaw37,
    MatLaw38,
    MatLaw40,
    MatLaw41,
    MatLaw42,
)

from .batch_031 import (
    MatLaw43,
    MatLaw44,
    MatLaw46,
    MatLaw48,
    MatLaw49,
    MatLaw50,
    MatLaw51,
    MatLaw52,
    MatLaw53,
)

from .batch_032 import (
    MatLaw54,
    MatLaw57,
    MatLaw58,
    MatLaw59,
    MatLaw60,
    MatLaw62,
    MatLaw63,
    MatLaw64,
    MatLaw65,
)

from .batch_033 import (
    MatLaw66,
    MatLaw68,
    MatLaw69,
    MatLaw70,
    MatLaw71,
    MatLaw72,
    MatLaw73,
    MatLaw74,
    MatLaw75,
)

from .batch_034 import (
    MatLaw76,
    MatLaw77,
    MatLaw78,
    MatLaw79,
    MatLaw80,
    MatLaw81,
    MatLaw82,
    MatLaw83,
    MatLaw84,
)

from .batch_035 import (
    MatLaw87,
    MatLaw88,
    MatLaw90,
    MatLaw92,
    MatLaw93,
    MatLaw94,
    MatLaw95,
    MatLaw97,
    MatLaw10,
)

from .batch_036 import (
    MatLaw101,
    MatLaw102,
    MatLaw103,
    MatLaw104,
    MatLaw106,
    MatLaw108,
    MatLaw109,
    MatLaw110,
    MatLaw111,
)

from .batch_037 import (
    MatLaw112,
    MatLaw113,
    MatLaw114,
    MatLaw115,
    MatLaw116,
    MatLaw117,
    MatLaw119,
    MatLaw121,
    MatLaw151,
)

from .batch_038 import (
    MatLaw200,
    MatPlasPredef,
    MatUserij,
    MergeRbody,
    MonvolAirbag1,
    MonvolArea,
    MonvolCommu1,
    MonvolFvmbag1,
    MonvolFvmbag2,
)

from .batch_039 import (
    MonvolGas,
    MonvolLfluid,
    MonvolPres,
    MoveFunct,
    Mpc,
    Nbcs,
    Node,
    NonlocalMat,
    Parameter,
)

from .batch_040 import (
    Part,
    Penta6,
    Perturb,
    PerturbFailBiquad,
    PerturbPartShell,
    PerturbPartSolid,
    Pload,
    Ply,
    Preload,
)

from .batch_041 import (
    PropInject1,
    PropInject2,
    PropPcompp,
    PropType0,
    PropType1,
    PropType2,
    PropType3,
    PropType4,
    PropType6,
)

from .batch_042 import (
    PropType8,
    PropType9,
    PropType10,
    PropType11,
    PropType12,
    PropType13,
    PropType14,
    PropType14,
    PropType15,
)

from .batch_043 import (
    PropType16,
    PropType17,
    PropType18,
    PropType19,
    PropType20,
    PropType21,
    PropType22,
    PropType23,
    PropType25,
)

from .batch_044 import (
    PropType26,
    PropType27,
    PropType28,
    PropType29,
    PropType30,
    PropType31,
    PropType32,
    PropType33,
    PropType34,
)

from .batch_045 import (
    PropType35,
    PropType36,
    PropType43,
    PropType44,
    PropType45,
    PropType46,
    PropType51,
    Quad,
    Radiation,
)

from .batch_046 import (
    Random,
    Rbe2,
    Rbe3,
    Rbody,
    RbodyLagmul,
    Refsta,
    RetractorSpring,
    Rlink,
    Rwall,
)

from .batch_047 import (
    RwallLagmul,
    RwallTherm,
    Sect,
    SectCircle,
    SectParal,
    Sensor,
    SensorAcce,
    SensorAndOr,
    SensorDist,
)

from .batch_048 import (
    SensorDistSurf,
    SensorEnergy,
    SensorGauge,
    SensorHic,
    SensorInter,
    SensorNot,
    SensorRbody,
    SensorRwall,
    SensorSect,
)

from .batch_049 import (
    SensorSens,
    SensorTime,
    SensorVel,
    SensorWork,
    Set,
    Sh3n,
    Shell,
    Shel16,
    SkewFix,
)

from .batch_050 import (
    SkewMov,
    SkewMov2,
    SlipringShell,
    SlipringSpring,
    SphInout,
    SphReserve,
    Sphbcs,
    Sphcel,
    Sphglo,
)

from .batch_051 import (
    Spring,
    Stack,
    Stamping,
    StateStrFile,
    Submodel,
    Subset,
    Surf,
    SurfBox,
    SurfDsurf,
)

from .batch_052 import (
    SurfEllips,
    SurfGrbricExt,
    SurfGrbricFree,
    SurfGrsh3n,
    SurfGrshel,
    SurfMat,
    SurfPart,
    SurfPlane,
    SurfProp,
)

from .batch_053 import (
    SurfSeg,
    SurfSubmodel,
    SurfSubset,
    SurfSurf,
    Table0,
    Table1,
    Tetra4,
    Tetra10,
    Th,
)

from .batch_054 import (
    ThAccel,
    ThBeam,
    ThBric,
    ThCluster,
    ThCylJo,
    ThFrame,
    ThFxbody,
    ThGauge,
    ThInter,
)

from .batch_055 import (
    ThMode,
    ThMonvol,
    ThNode,
    ThNstrand,
    ThPart,
    ThQuad,
    ThRbody,
    ThRetractor,
    ThRwall,
)

from .batch_056 import (
    ThSectio,
    ThSh3n,
    ThShel,
    ThSlipring,
    ThSphFlow,
    ThSphcel,
    ThSpring,
    ThSubs,
    ThSurf,
)

from .batch_057 import (
    ThTria,
    ThTruss,
    ThermStressMat,
    Thpart,
    ThpartGrbeam,
    ThpartGrbric,
    ThpartGrquad,
    ThpartGrsh3n,
    ThpartGrshel,
)

from .batch_058 import (
    ThpartGrspri,
    ThpartGrtrus,
    Title,
    Transform,
    TransformMatrix,
    TransformPosition,
    TransformRot,
    TransformSca,
    TransformSym,
)

from .batch_059 import TransformTra, Tria, Truss, Unit, Upwind, ViscProny, Xelem, Xref

# --- Build the keyword registry --------------------------------------------------------------
keywords = (
    Accel,
    Activ,
    Admas,
    AdmeshGlobal,
    AdmeshSet,
    AdmeshStateSh3n,
    AdmeshStateShell,
    ALEBcs,
    ALEClose,
    ALEGridDisp,
    ALEGridDonea,
    ALEGridLaplacian,
    ALEGridSpring,
    ALEGridStandard,
    ALEGridVolume,
    ALEGridZero,
    ALELinkVel,
    ALEMat,
    ALEMuscl,
    ALESolverFint,
    Ams,
    Analy,
    AnimVers,
    Bcs,
    BcsCyclic,
    BcsLagmul,
    Beam,
    Begin,
    BemDaa,
    BemFlow,
    Box,
    BoxBox,
    Bric20,
    Brick,
    CheckRfileOff,
    Cload,
    Cluster,
    Cnode,
    Convec,
    CylJoint,
    Damp,
    DampInter,
    Def_Shell,
    Def_Solid,
    DefaultInterType11,
    DefaultInterType19,
    DefaultInterType2,
    DefaultInterType24,
    DefaultInterType25,
    DefaultInterType7,
    DfsDetcord,
    DfsDetline,
    DfsDetlineNode,
    DfsDetplan,
    DfsDetplanNode,
    DfsDetpoint,
    DfsDetpointNode,
    DfsLaser,
    DfsWavSha,
    Drape,
    EbcsFluxout,
    EbcsGradp0,
    EbcsInip,
    EbcsIniv,
    EbcsInlet,
    EbcsMonvol,
    EbcsNormv,
    EbcsNrf,
    EbcsPres,
    EbcsValvin,
    EbcsValvout,
    EbcsVel,
    Eig,
    Encrypt,
    End,
    EosCompaction,
    EosGruneisen,
    EosIdealGas,
    EosIdealGasVt,
    EosLinear,
    EosLszk,
    EosMurnaghan,
    EosNasg,
    EosNobleAbel,
    EosOsborne,
    EosPolynomial,
    EosPuff,
    EosSesame,
    EosStiffGas,
    EosTillotson,
    Eref,
    EulerMat,
    Fail,
    FailAlter,
    FailBiquad,
    FailChang,
    FailCockcroft,
    FailConnect,
    FailEmc,
    FailEnergy,
    FailFabric,
    FailFld,
    FailGene1,
    FailGurson,
    FailHashin,
    FailHcDsse,
    FailJohnson,
    FailLadDama,
    FailMullinsOr,
    FailNxt,
    FailOrthbiquad,
    FailOrthstrain,
    FailPuck,
    FailRtcl,
    FailSahraei,
    FailSnconnect,
    FailSpalling,
    FailTab1,
    FailTbutcher,
    FailTensstrain,
    FailUseri,
    FailVisual,
    FailWierzbicki,
    FailWilkins,
    FrameFix,
    FrameMov,
    FrameMov2,
    FrameNod,
    FricOrient,
    Friction,
    Func2d,
    Funct,
    FunctSmooth,
    Fxbody,
    Gauge,
    GaugeSph,
    Gjoint,
    Grav,
    Grbeam,
    Grbric,
    Grnod,
    Grpart,
    Grquad,
    Grsh3n,
    Grshel,
    Grspri,
    Grtria,
    Grtrus,
    HeatMat,
    Impacc,
    Impdisp,
    ImpdispFgeo,
    Impflux,
    Implicit,
    Imptemp,
    Impvel,
    ImpvelFgeo,
    ImpvelLagmul,
    InibeamAux,
    InibeamFull,
    Inibri,
    Inicrack,
    Inigrav,
    Inimap1d,
    Inimap1dFile,
    Inimap2d,
    Inimap2dFile,
    Iniqua,
    IniquaDens,
    IniquaEner,
    IniquaEpsp,
    IniquaStress,
    Inish3Aux,
    Inish3Epsp,
    Inish3EpspF,
    Inish3OrthLoc,
    Inish3Ortho,
    Inish3ScaleYld,
    Inish3StraF,
    Inish3StraFGlob,
    Inish3StrsF,
    Inish3StrsFGlob,
    Inish3Thick,
    InisheAux,
    InisheEpsp,
    InisheEpspF,
    InisheFail,
    InisheOrthLoc,
    InisheOrtho,
    InisheScaleYld,
    InisheStraF,
    InisheStraFGlob,
    InisheStrsF,
    InisheStrsFGlob,
    InisheThick,
    InispriFull,
    InispriFull,
    Inista,
    Initemp,
    InitrussFull,
    Inivel,
    InivelAxis,
    InivelFvm,
    InivelNode,
    Inivol,
    InterHertzType17,
    InterLagdtType7,
    InterLagmulType16,
    InterLagmulType17,
    InterLagmulType2,
    InterLagmulType7,
    InterSub,
    InterType1,
    InterType10,
    InterType11,
    InterType12,
    InterType14,
    InterType15,
    InterType18,
    InterType19,
    InterType2,
    InterType21,
    InterType22,
    InterType23,
    InterType24,
    InterType25,
    InterType3,
    InterType5,
    InterType6,
    InterType7,
    InterType8,
    InterType9,
    Ioflag,
    Key,
    Lagmul,
    LeakMat,
    Line,
    LoadCentri,
    LoadPblast,
    LoadPfluid,
    MadymoExfem,
    MatBKEps,
    MatGas,
    MatKEps,
    MatLaw0,
    MatLaw1,
    MatLaw10,
    MatLaw10,
    MatLaw101,
    MatLaw102,
    MatLaw103,
    MatLaw104,
    MatLaw106,
    MatLaw108,
    MatLaw109,
    MatLaw11,
    MatLaw110,
    MatLaw111,
    MatLaw112,
    MatLaw113,
    MatLaw114,
    MatLaw115,
    MatLaw116,
    MatLaw117,
    MatLaw119,
    MatLaw12,
    MatLaw121,
    MatLaw14,
    MatLaw15,
    MatLaw151,
    MatLaw16,
    MatLaw18,
    MatLaw19,
    MatPlasJohns,
    MatLaw20,
    MatLaw200,
    MatLaw21,
    MatLaw22,
    MatLaw23,
    MatLaw24,
    MatLaw25,
    MatLaw26,
    MatLaw27,
    MatLaw28,
    MatLaw3,
    MatLaw32,
    MatLaw33,
    MatLaw34,
    MatLaw35,
    MatLaw36,
    MatLaw37,
    MatLaw38,
    MatLaw4,
    MatLaw40,
    MatLaw41,
    MatLaw42,
    MatLaw43,
    MatLaw44,
    MatLaw46,
    MatLaw48,
    MatLaw49,
    MatLaw5,
    MatLaw50,
    MatLaw51,
    MatLaw52,
    MatLaw53,
    MatLaw54,
    MatLaw57,
    MatLaw58,
    MatLaw59,
    MatLaw6,
    MatLaw60,
    MatLaw62,
    MatLaw63,
    MatLaw64,
    MatLaw65,
    MatLaw66,
    MatLaw68,
    MatLaw69,
    MatLaw70,
    MatLaw71,
    MatLaw72,
    MatLaw73,
    MatLaw74,
    MatLaw75,
    MatLaw76,
    MatLaw77,
    MatLaw78,
    MatLaw79,
    MatLaw80,
    MatLaw81,
    MatLaw82,
    MatLaw83,
    MatLaw84,
    MatLaw87,
    MatLaw88,
    MatLaw90,
    MatLaw92,
    MatLaw93,
    MatLaw94,
    MatLaw95,
    MatLaw97,
    MatPlasPredef,
    MatPlasZeril,
    MatUserij,
    MergeRbody,
    MonvolAirbag1,
    MonvolArea,
    MonvolCommu1,
    MonvolFvmbag1,
    MonvolFvmbag2,
    MonvolGas,
    MonvolLfluid,
    MonvolPres,
    MoveFunct,
    Mpc,
    Nbcs,
    Node,
    NonlocalMat,
    Parameter,
    Part,
    Penta6,
    Perturb,
    PerturbFailBiquad,
    PerturbPartShell,
    PerturbPartSolid,
    Pload,
    Ply,
    Preload,
    PropInject1,
    PropInject2,
    PropPcompp,
    PropType0,
    PropType1,
    PropType10,
    PropType11,
    PropType12,
    PropType13,
    PropType14,
    PropType14,
    PropType15,
    PropType16,
    PropType17,
    PropType18,
    PropType19,
    PropType2,
    PropType20,
    PropType21,
    PropType22,
    PropType23,
    PropType25,
    PropType26,
    PropType27,
    PropType28,
    PropType29,
    PropType3,
    PropType30,
    PropType31,
    PropType32,
    PropType33,
    PropType34,
    PropType35,
    PropType36,
    PropType4,
    PropType43,
    PropType44,
    PropType45,
    PropType46,
    PropType51,
    PropType6,
    PropType8,
    PropType9,
    Quad,
    Radiation,
    Random,
    Rbe2,
    Rbe3,
    Rbody,
    RbodyLagmul,
    Refsta,
    RetractorSpring,
    Rlink,
    Rwall,
    RwallLagmul,
    RwallTherm,
    Sect,
    SectCircle,
    SectParal,
    Sensor,
    SensorAcce,
    SensorAndOr,
    SensorDist,
    SensorDistSurf,
    SensorEnergy,
    SensorGauge,
    SensorHic,
    SensorInter,
    SensorNot,
    SensorRbody,
    SensorRwall,
    SensorSect,
    SensorSens,
    SensorTime,
    SensorVel,
    SensorWork,
    Set,
    Sh3n,
    Shel16,
    Shell,
    SkewFix,
    SkewMov,
    SkewMov2,
    SlipringShell,
    SlipringSpring,
    SphInout,
    SphReserve,
    Sphbcs,
    Sphcel,
    Sphglo,
    Spring,
    Stack,
    Stamping,
    StateStrFile,
    Submodel,
    Subset,
    Surf,
    SurfBox,
    SurfDsurf,
    SurfEllips,
    SurfGrbricExt,
    SurfGrbricFree,
    SurfGrsh3n,
    SurfGrshel,
    SurfMat,
    SurfPart,
    SurfPlane,
    SurfProp,
    SurfSeg,
    SurfSubmodel,
    SurfSubset,
    SurfSurf,
    Table0,
    Table1,
    Tetra10,
    Tetra4,
    Th,
    ThAccel,
    ThBeam,
    ThBric,
    ThCluster,
    ThCylJo,
    ThFrame,
    ThFxbody,
    ThGauge,
    ThInter,
    ThMode,
    ThMonvol,
    ThNode,
    ThNstrand,
    ThPart,
    ThQuad,
    ThRbody,
    ThRetractor,
    ThRwall,
    ThSectio,
    ThSh3n,
    ThShel,
    ThSlipring,
    ThSphFlow,
    ThSphcel,
    ThSpring,
    ThSubs,
    ThSurf,
    ThTria,
    ThTruss,
    ThermStressMat,
    Thpart,
    ThpartGrbeam,
    ThpartGrbric,
    ThpartGrquad,
    ThpartGrsh3n,
    ThpartGrshel,
    ThpartGrspri,
    ThpartGrtrus,
    Title,
    Transform,
    TransformMatrix,
    TransformPosition,
    TransformRot,
    TransformSca,
    TransformSym,
    TransformTra,
    Tria,
    Truss,
    Unit,
    Upwind,
    ViscProny,
    Xelem,
    Xref,
)
KEYWORD_REGISTRY = {}
for keyword in keywords:
    KEYWORD_REGISTRY[keyword.__name__.upper()] = keyword
