from ._starter import KEYWORD_REGISTRY as STARTER_KEYWORD_REGISTRY
from ._engine import KEYWORD_REGISTRY as ENGINE_KEYWORD_REGISTRY

KEYWORD_REGISTRY = {
    "starter": STARTER_KEYWORD_REGISTRY,
    "engine": ENGINE_KEYWORD_REGISTRY,
}
